### ISSUE TITLE
Create a new test with an strange Sequences issue

### ISSUE THREAD

**Issue by rocboronat** [Fewlaps/mention-detector#8]
`Test
    public void getSequences_shouldNotCrash_whenPassingAQuitNowText1() throws InterruptedException {
        String text = "@Twinx@ Texie@sabertooth89 great Quit!!";
        List<Sequence> sequences = new MentionDetector(text).getSequences();
        assertThat(sequences).hasSize(1);
    }
`

... right now, it breaks, 'cause it returns two Sequences instead of only one.

**Comment by EsteveAguilera** [comment]
I'm adding some info I've found when debugging the test you added: 

**parseMention()** detects 3 mentions:

- (at)Twinx
- (at)Texie
- (at)sabertooth89

**getSequences()** detects 2 sequences:

- 0-12 -> (at)Twinx(at) Texie
- 13-26 -> (at)sabertooth89 

You say that it should return 1 sequence instead of 2 so the real mention/sequence should be just **(at)Twinx**. Am I right?

**Comment by rocboronat** [comment]
Mmmm that's what I thought three years ago, haha! Now I think that "@ Texie" shouldn't be considered a mention. What do you think? 😄

**Comment by EsteveAguilera** [comment]
Ouch, I didn't realize this was a 3 y.o issue 😅

Just to see what others consider a mention, and what doesn’t, I’ve done a test on TW, and found something different...

![2df5e027-ecfc-403c-a6c4-e1217f5bbf96](https://user-images.githubusercontent.com/6932449/52891765-64096d80-318d-11e9-9bf4-798ed2a17aeb.jpeg)

And I agree with TW, a mention is a mention, you type it wrong? Sorry, but no mention....

**Comment by rocboronat** [comment]
Hahaha good test! Then we should edit the library to catch this case.

Sounds not that easy, by the way, hahaha!

**Comment by EsteveAguilera** [comment]
🤔This sounds me like a new issue. Maybe something like "change the definition of mention".
What do you think @rocboronat?

**Comment by rocboronat** [comment]
That's true! :·)

**Comment by rocboronat** [comment]
Let's move the discussion to #10
